"""
Pre-analyzer (PreAnalyzer)
========================

Corresponds to human cognition stage 2: "quickly flip through
the document before detailed analysis."

Obtains a "first impression" of a document at minimal cost (~10ms)
before layout analysis:

    1. Text layer check:       digital vs scanned
    2. Page count:             scale estimation
    3. First page content:     table-dominant vs text-dominant vs mixed
    4. Quality assessment:     text clarity / layout regularity
    5. Complexity assessment:  decide compute budget
    6. Strategy recommendation: fast / standard / deep

Output ``PreAnalysisResult`` (frozen) is stored in
``BaseResult.metadata`` for Orchestrator and Middleware to tune
their parameters dynamically.
"""
from __future__ import annotations


import logging
import dataclasses
from collections import Counter
from typing import Any, Dict, List, Tuple

logger = logging.getLogger(__name__)


@dataclasses.dataclass(frozen=True)
class PreAnalysisResult:
    """
    Pre-analysis result (immutable).

    Generated by PreAnalyzer before extraction, providing decision
    inputs for all subsequent pipeline stages.
    """
    # Basic properties
    has_text_layer: bool = True
    num_pages: int = 0

    # Content type
    content_type: str = "unknown"
    # "table_dominant"  — tables dominate (bank statement, invoice)
    # "text_dominant"   — pure text (contract, report)
    # "mixed"           — mixed layout
    # "scanned"         — scanned document (no/minimal text layer)

    # Quality score (0.0-1.0)
    quality_score: float = 1.0
    # 1.0 = clear digital document
    # 0.7 = slightly blurry / has watermark
    # 0.3 = low-quality scanned document

    # Complexity
    complexity_level: str = "medium"
    # "simple"  — single table, < 10 pages
    # "medium"  — multiple content blocks, 10-50 pages
    # "complex" — complex mixed layout, > 50 pages, multiple tables

    # Recommended strategy
    recommended_strategy: str = "standard"
    # "fast"     — skip non-essential middlewares, simplified extraction
    # "standard" — standard pipeline
    # "deep"     — enable high-DPI OCR, more validation dimensions

    # First page preview
    first_page_preview: str = ""

    # Layout statistics
    estimated_table_pages: int = 0
    estimated_scanned_pages: int = 0

    # Layout homogeneity (indicator of structurally uniform documents)
    layout_homogeneous: bool = False
    # True  = sampled pages share the same layout structure (e.g., consistent table per page)
    # False = pages have significant layout variations (e.g., mixed reports)

    # Detected document language
    detected_language: str = "unknown"
    # Examples: "zh", "en", "ja", "ko", "mixed", "unknown"

    # Strategy parameters (consumed directly by Orchestrator, replacing hardcoded if/else)
    strategy_params: dict = dataclasses.field(default_factory=dict)

    # Average image quality score for scanned pages (0-100)
    # 100 = high-res clear scan, 85+ = clear, 60-85 = medium, <60 = low quality
    avg_image_quality: int = 100

    # Per-page quality map: tuple of (page_idx, quality_score) pairs.
    # Only populated for sampled pages; unsampled pages should use
    # avg_image_quality as fallback.  Consumed by AdaptiveQualityRouter
    # for zone-level DPI decisions.
    page_quality_map: tuple = ()

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dict for storage in BaseResult.metadata."""
        return dataclasses.asdict(self)


class PreAnalyzer:
    """
    Pre-analysis engine.

    Design principles:
        - Ultra-low cost: reads only 1-3 pages, ~10ms total
        - Read-only: never modifies the document
        - Comprehensive: 5 dimensions of "first impression"

    Usage::

        pre = PreAnalyzer()
        result = pre.analyze(fitz_doc)
        # result.recommended_strategy -> "fast" / "standard" / "deep"
    """

    def analyze(self, fitz_doc) -> PreAnalysisResult:
        """
        Analyze document and produce a PreAnalysisResult.

        Args:
            fitz_doc: An opened PyMuPDF document object.
        """
        num_pages = len(fitz_doc)
        if num_pages == 0:
            return PreAnalysisResult(num_pages=0, content_type="unknown")

        # -- Step 1: Text layer check --
        has_text, text_density = self._check_text_layer(fitz_doc)

        # -- Step 2: First page analysis --
        first_page = fitz_doc[0]
        first_page_stats = self._analyze_page(first_page, 0)
        first_page_preview = first_page.get_text()[:200].strip()

        # -- Step 3: Quick full-document scan (statistics only) --
        table_pages = 0
        scanned_pages = 0
        image_quality_scores: List[int] = []
        page_quality_pairs: List[tuple] = []  # (page_idx, quality_score)
        page_fingerprints: List[tuple] = []  # for layout homogeneity check

        # Scan at most first 10 pages + last 2 pages (typical for bank statements)
        sample_pages = list(range(min(10, num_pages)))
        if num_pages > 10:
            sample_pages.extend([num_pages - 2, num_pages - 1])

        for idx in sample_pages:
            if idx >= num_pages:
                continue
            stats = self._analyze_page(fitz_doc[idx], idx)
            if stats["has_table"]:
                table_pages += 1
            if stats["is_scanned"]:
                scanned_pages += 1
                image_quality_scores.append(stats["image_quality_score"])
            page_quality_pairs.append((idx, stats["image_quality_score"]))
            # Collect structural fingerprints (for layout homogeneity detection)
            page_fingerprints.append(
                (stats["x_column_count"], stats["has_table"], stats["text_blocks"])
            )

        # -- Step 3.5: Layout homogeneity check --
        layout_homogeneous = self._check_layout_homogeneity(page_fingerprints)

        # -- Step 4: Content type determination --
        content_type = self._determine_content_type(
            has_text, text_density, first_page_stats,
            table_pages, scanned_pages, len(sample_pages),
        )

        # -- Step 5: Quality assessment --
        quality_score = self._assess_quality(
            has_text, text_density, first_page_stats, scanned_pages,
        )

        # -- Step 6: Complexity assessment --
        complexity_level = self._assess_complexity(
            num_pages, content_type, first_page_stats,
        )

        # -- Step 7: Strategy recommendation --
        strategy = self._recommend_strategy(
            complexity_level, quality_score, content_type,
        )

        # -- Step 8: Strategy parameterisation --
        strategy_params = self._build_strategy_params(
            strategy, content_type, layout_homogeneous,
            has_text, quality_score,
        )

        # -- Step 9: Language detection --
        detected_language = self._detect_language(first_page_preview)

        result = PreAnalysisResult(
            has_text_layer=has_text,
            num_pages=num_pages,
            content_type=content_type,
            quality_score=round(quality_score, 2),
            complexity_level=complexity_level,
            recommended_strategy=strategy,
            first_page_preview=first_page_preview,
            estimated_table_pages=table_pages,
            estimated_scanned_pages=scanned_pages,
            layout_homogeneous=layout_homogeneous,
            detected_language=detected_language,
            strategy_params=strategy_params,
            avg_image_quality=(
                int(sum(image_quality_scores) / len(image_quality_scores))
                if image_quality_scores else 100
            ),
            page_quality_map=tuple(page_quality_pairs),
        )

        logger.info(
            f"[DocMirror] PreAnalyzer \u25b6 "
            f"pages={num_pages} | type={content_type} | "
            f"quality={quality_score:.2f} | complexity={complexity_level} | "
            f"strategy={strategy} | homogeneous={layout_homogeneous} | "
            f"lang={detected_language}"
        )

        return result

    # ===============================================================================
    # Internal Analysis Methods
    # ===============================================================================

    def _check_text_layer(self, fitz_doc) -> Tuple[bool, float]:
        """
        Check text layer presence and density.

        Returns:
            (has_text, density): density = avg chars per page / 1000
        """
        total_chars = 0
        check_pages = min(3, len(fitz_doc))

        for i in range(check_pages):
            text = fitz_doc[i].get_text()
            total_chars += len(text.strip())

        avg_chars = total_chars / check_pages if check_pages else 0
        has_text = avg_chars > 30  # fewer than 30 chars -> essentially no text
        density = avg_chars / 1000

        return has_text, density

    def _analyze_page(self, page, page_idx: int) -> Dict[str, Any]:
        """
        Quick single-page analysis (~5ms).

        Extracts:
            - Text block count, image block count
            - Whether page has tables (find_tables)
            - Whether page is scanned (very few chars + large images)
            - Text region count, image coverage ratio
        """
        rect = page.rect
        page_area = rect.width * rect.height
        text_dict = page.get_text("dict", flags=0)
        text_blocks = [b for b in text_dict.get("blocks", []) if b.get("type") == 0]
        image_blocks = [b for b in text_dict.get("blocks", []) if b.get("type") == 1]

        # Total character count
        total_chars = sum(
            len(span.get("text", ""))
            for b in text_blocks
            for line in b.get("lines", [])
            for span in line.get("spans", [])
        )

        # Image coverage ratio
        image_area = 0
        for b in image_blocks:
            bx = b["bbox"]
            image_area += max(0, (bx[2] - bx[0]) * (bx[3] - bx[1]))
        image_coverage = image_area / page_area if page_area else 0

        # Table detection
        has_table = False
        table_count = 0
        try:
            tables = page.find_tables()
            table_count = len(tables.tables)
            has_table = table_count > 0
        except Exception as exc:
            logger.debug(f"operation: suppressed {exc}")

        # Scanned document detection
        is_scanned = (total_chars < 50 and image_coverage > 0.4)

        # Text density (column distribution, used for table detection)
        x_positions = set()
        for b in text_blocks:
            for line in b.get("lines", []):
                for span in line.get("spans", []):
                    if span.get("text", "").strip():
                        x_positions.add(round(span["bbox"][0] / 20) * 20)

        return {
            "text_blocks": len(text_blocks),
            "image_blocks": len(image_blocks),
            "total_chars": total_chars,
            "image_coverage": image_coverage,
            "has_table": has_table,
            "table_count": table_count,
            "is_scanned": is_scanned,
            "x_column_count": len(x_positions),  # wide column spread -> table indicator
            "image_quality_score": self._assess_image_quality(page) if is_scanned else 100,
        }

    def _determine_content_type(
        self,
        has_text: bool,
        text_density: float,
        first_page: Dict,
        table_pages: int,
        scanned_pages: int,
        sample_size: int,
    ) -> str:
        """Determine content type."""
        if not has_text or (scanned_pages > sample_size * 0.5):
            return "scanned"

        table_ratio = table_pages / sample_size if sample_size else 0

        if table_ratio >= 0.6:
            return "table_dominant"
        elif table_ratio <= 0.2 and first_page["x_column_count"] <= 3:
            return "text_dominant"
        else:
            return "mixed"

    def _assess_quality(
        self,
        has_text: bool,
        text_density: float,
        first_page: Dict,
        scanned_pages: int,
    ) -> float:
        """Assess quality (0-1)."""
        if not has_text:
            return 0.3  # scanned document baseline

        score = 1.0

        # Low text density -> quality drop
        if text_density < 0.1:
            score -= 0.3
        elif text_density < 0.5:
            score -= 0.1

        # High image coverage with text -> possible watermark
        if first_page["image_coverage"] > 0.3 and has_text:
            score -= 0.1

        # Has scanned pages -> quality drop
        if scanned_pages > 0:
            score -= 0.2

        return max(0.1, min(1.0, score))

    def _assess_image_quality(self, page) -> int:
        """Assess image quality for scanned pages (0-100).

        Uses a Laplacian variance-based blur detection on a low-DPI
        rendering (~5ms cost) to determine scan clarity.

        Score interpretation:
            85-100: Clear scan → single-pass OCR sufficient
            60-84:  Medium quality → standard multi-scale OCR
            0-59:   Low quality → image enhancement + full OCR pipeline

        Returns:
            Quality score 0-100.
        """
        try:
            import numpy as np
            # Render page at low DPI for speed (~3ms)
            pix = page.get_pixmap(dpi=72)
            img = np.frombuffer(pix.samples, dtype=np.uint8).reshape(
                pix.height, pix.width, pix.n
            )

            # Convert to grayscale
            if pix.n >= 3:
                gray = np.mean(img[:, :, :3], axis=2).astype(np.uint8)
            else:
                gray = img[:, :, 0]

            # Laplacian variance — measures focus/sharpness
            # Manual Laplacian kernel convolution (avoids cv2 dependency)
            from scipy.ndimage import laplace  # type: ignore
            lap = laplace(gray.astype(np.float64))
            lap_var = float(np.var(lap))

            # Scale: 0-1000+ variance → 0-100 score
            # Empirical mapping: var<50=blurry, 50-200=ok, 200+=sharp
            if lap_var >= 200:
                score = 100
            elif lap_var >= 50:
                score = 60 + int((lap_var - 50) / 150 * 40)
            else:
                score = int(lap_var / 50 * 60)

            return max(0, min(100, score))

        except ImportError:
            # scipy not available — use simpler contrast-based heuristic
            try:
                import numpy as np
                pix = page.get_pixmap(dpi=72)
                img = np.frombuffer(pix.samples, dtype=np.uint8)
                # Standard deviation of pixel values as quality proxy
                std = float(np.std(img))
                # Low std = flat/uniform = likely blurry or blank
                return max(0, min(100, int(std * 1.5)))
            except Exception as exc:
                logger.debug(f"operation: suppressed {exc}")
                return 70  # safe fallback
        except Exception as exc:
            logger.debug(f"operation: suppressed {exc}")
            return 70  # safe fallback

    def _assess_complexity(
        self,
        num_pages: int,
        content_type: str,
        first_page: Dict,
    ) -> str:
        """Assess complexity level."""
        # Page count dimension
        if num_pages > 50:
            return "complex"

        # Mixed layout
        if content_type == "mixed":
            return "complex" if num_pages > 20 else "medium"

        # Scanned documents are always more complex
        if content_type == "scanned":
            return "complex" if num_pages > 10 else "medium"

        # Simple single-table document
        if content_type == "table_dominant" and num_pages <= 10:
            return "simple"

        if content_type == "text_dominant" and num_pages <= 5:
            return "simple"

        return "medium"

    def _recommend_strategy(
        self,
        complexity: str,
        quality: float,
        content_type: str,
    ) -> str:
        """Recommend processing strategy."""
        if complexity == "simple" and quality >= 0.8:
            return "fast"

        if complexity == "complex" or quality < 0.5:
            return "deep"

        return "standard"

    # ===============================================================================
    # Layout Homogeneity + Strategy Parameterisation
    # ===============================================================================

    def _check_layout_homogeneity(
        self, fingerprints: List[tuple],
    ) -> bool:
        """Check whether sampled pages share a consistent layout.

        Homogeneity criterion: >=80% of sampled pages share the same
        (x_column_count, has_table) fingerprint.
        Returns False when fewer than 3 pages are sampled.
        """
        if len(fingerprints) < 3:
            return False

        # Focus on two key dimensions: (x_column_count, has_table)
        patterns = [(fp[0], fp[1]) for fp in fingerprints]
        most_common, count = Counter(patterns).most_common(1)[0]
        ratio = count / len(patterns)
        return ratio >= 0.8

    def _build_strategy_params(
        self,
        strategy: str,
        content_type: str,
        layout_homogeneous: bool,
        has_text: bool,
        quality_score: float,
    ) -> dict:
        """Build concrete strategy parameters dict from pre-analysis.

        These parameters are consumed directly by Orchestrator and
        Middlewares, avoiding hardcoded if/else on strategy strings.
        """
        params: Dict[str, Any] = {}

        # Watermark filter: can skip for high-quality text-dominant documents
        params["skip_watermark_filter"] = (
            content_type == "text_dominant" and quality_score >= 0.9
        )

        # Docling: consider enabling for standard/deep with text layer
        params["enable_docling"] = (
            strategy in ("standard", "deep") and has_text
        )

        # Table extraction method priority
        if content_type == "table_dominant":
            params["table_method_priority"] = [
                "lines", "hline_columns", "rect_columns", "text",
            ]
        else:
            params["table_method_priority"] = ["lines", "text"]

        # First-page structure reuse: homogeneous + table-dominant documents
        params["reuse_first_page_structure"] = (
            layout_homogeneous and content_type == "table_dominant"
        )

        # LLM enablement recommendation
        params["enable_llm"] = (strategy == "deep")

        # P2: OCR DPI recommendation based on image quality
        # Higher quality → single pass at 200 DPI (fast)
        # Lower quality → multi-scale fusion needed
        if quality_score < 0.5:
            params["ocr_dpi"] = [150, 200, 300]  # full multi-scale
        elif quality_score < 0.8:
            params["ocr_dpi"] = [200, 300]  # two passes
        else:
            params["ocr_dpi"] = [200]  # single pass

        return params

    def _detect_language(self, text_sample: str) -> str:
        """Detect document language.

        Uses fast-langdetect (if installed) or a character-statistics
        fallback method.

        Args:
            text_sample: Text sample (typically first 200 chars of page 1).

        Returns:
            Language code: "zh", "en", "ja", "ko", "mixed", or "unknown"
        """
        if not text_sample or len(text_sample.strip()) < 10:
            return "unknown"

        # Try fast-langdetect
        try:
            from fast_langdetect import detect  # type: ignore
            result = detect(text_sample)
            if isinstance(result, dict):
                return result.get("lang", "unknown")
            elif isinstance(result, str):
                return result
        except ImportError:
            pass  # fast-langdetect not installed, use fallback
        except Exception as exc:
            logger.debug(f"operation: suppressed {exc}")

        # Fallback: simple character-statistics based detection
        cjk_count = 0
        latin_count = 0
        for ch in text_sample:
            cp = ord(ch)
            if (0x4E00 <= cp <= 0x9FFF or 0x3400 <= cp <= 0x4DBF
                    or 0x20000 <= cp <= 0x2A6DF):
                cjk_count += 1
            elif (0x0041 <= cp <= 0x005A or 0x0061 <= cp <= 0x007A):
                latin_count += 1

        total = cjk_count + latin_count
        if total == 0:
            return "unknown"

        cjk_ratio = cjk_count / total
        if cjk_ratio > 0.7:
            return "zh"  # simplified: CJK-dominant treated as Chinese
        elif cjk_ratio < 0.1:
            return "en"
        else:
            return "mixed"
